# Generated by Django 5.2.7 on 2025-11-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unid', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade')),
                ('nome_unid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('cs_tt_maquina', models.IntegerField(blank=True, null=True, verbose_name='Código Total Máquina')),
                ('descr_maquina', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Máquina')),
                ('cd_maquina', models.BigIntegerField(db_index=True, unique=True, verbose_name='Código Máquina')),
                ('cd_setormanut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Setor Manutenção')),
                ('descr_setormanut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Setor Manutenção')),
                ('cd_priomaqutv', models.IntegerField(blank=True, null=True, verbose_name='Código Prioridade Máquina')),
                ('nro_patrimonio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Patrimônio')),
                ('cd_modelo', models.IntegerField(blank=True, null=True, verbose_name='Código Modelo')),
                ('cd_grupo', models.IntegerField(blank=True, null=True, verbose_name='Código Grupo')),
                ('cd_tpcentativ', models.IntegerField(blank=True, null=True, verbose_name='Código Tipo Centro Atividade')),
                ('descr_gerenc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Gerência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['cd_maquina'],
            },
        ),
    ]
