# Generated by Django 5.2.7 on 2025-11-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unid', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade')),
                ('nome_unid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('cd_unid_exec', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade Execução')),
                ('nome_unid_exec', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade Execução')),
                ('cd_setormanut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Setor Manutenção')),
                ('descr_setormanut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Setor Manutenção')),
                ('cd_tpcentativ', models.IntegerField(blank=True, null=True, verbose_name='Código Tipo Centro Atividade')),
                ('descr_abrev_tpcentativ', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Abrev Centro Atividade')),
                ('cd_maquina', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Código Máquina')),
                ('descr_maquina', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Máquina')),
                ('cd_ordemserv', models.BigIntegerField(db_index=True, unique=True, verbose_name='Código Ordem Serviço')),
                ('dt_entrada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Entrada')),
                ('dt_abertura_solicita', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Abertura Solicitação')),
                ('cd_func_solic_os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Funcionário Solicitante OS')),
                ('nm_func_solic_os', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funcionário Solicitante OS')),
                ('descr_queixa', models.TextField(blank=True, null=True, verbose_name='Descrição Queixa')),
                ('exec_tarefas', models.TextField(blank=True, null=True, verbose_name='Execução Tarefas')),
                ('cd_func_exec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Funcionário Executor')),
                ('nm_func_exec', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funcionário Executor')),
                ('descr_obsordserv', models.TextField(blank=True, null=True, verbose_name='Descrição Observações Ordem Serviço')),
                ('dt_encordmanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Encerramento Ordem Manutenção')),
                ('dt_aberordser', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Abertura Ordem Serviço')),
                ('dt_iniparmanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Início Parada Manutenção')),
                ('dt_fimparmanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Fim Parada Manutenção')),
                ('dt_prev_exec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Prevista Execução')),
                ('cd_tpordservtv', models.IntegerField(blank=True, null=True, verbose_name='Código Tipo Ordem Serviço')),
                ('descr_tpordservtv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Tipo Ordem Serviço')),
                ('descr_sitordsetv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Situação Ordem Serviço')),
                ('descr_recomenos', models.TextField(blank=True, null=True, verbose_name='Descrição Recomendações OS')),
                ('descr_seqplamanu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Sequência Plano Manutenção')),
                ('cd_tpmanuttv', models.IntegerField(blank=True, null=True, verbose_name='Código Tipo Manutenção')),
                ('descr_tpmanuttv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Tipo Manutenção')),
                ('cd_clasorigos', models.IntegerField(blank=True, null=True, verbose_name='Código Classificação Origem OS')),
                ('descr_clasorigos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Classificação Origem OS')),
                ('cd_func_exec_os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Funcionário Executor OS')),
                ('nm_func_exec_os', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funcionário Executor OS')),
                ('dt_ficapomanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Ficha Ponto Manutenção')),
                ('dt_inic_iteficmanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Início Item Ficha Manutenção')),
                ('dt_fim_iteficmanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Fim Item Ficha Manutenção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço Corretiva',
                'verbose_name_plural': 'Ordens de Serviço Corretivas',
                'ordering': ['-cd_ordemserv'],
            },
        ),
    ]
