# Generated by Django 5.2.7 on 2025-11-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ordemservicocorretiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.IntegerField(db_index=True, unique=True, verbose_name='CA')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('indice', models.IntegerField(blank=True, null=True, verbose_name='Índice')),
                ('encarregado_responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Encarregado Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Centro de Atividade',
                'verbose_name_plural': 'Centros de Atividade',
                'ordering': ['ca'],
            },
        ),
    ]
