# Generated by Django 5.2.7 on 2025-11-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_centroatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/fotos/', verbose_name='Foto da Máquina'),
        ),
    ]
