# Generated by Django 5.2.7 on 2025-11-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_maquina_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='placa_identificacao',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/placas/', verbose_name='Placa de Identificação'),
        ),
    ]
