# Generated by Django 5.2.7 on 2025-11-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_maquina_placa_identificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutentor',
            fields=[
                ('Cadastro', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Cadastro')),
                ('Nome', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nome')),
                ('Admissao', models.DateField(blank=True, null=True, verbose_name='Admissão')),
                ('Cargo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cargo')),
                ('Posto', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Posto')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário Início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário Fim')),
                ('tempo_trabalho', models.CharField(max_length=250, verbose_name='Tempo de Trabalho')),
                ('tipo', models.CharField(choices=[('Eletricista', 'Eletricista'), ('Mecânico', 'Mecânico'), ('Eletromecânico', 'Eletromecânico'), ('Operador ETE/ETA', 'Operador ETE/ETA')], max_length=25, verbose_name='Tipo')),
                ('turno', models.CharField(choices=[('Turno A', 'Turno A'), ('Turno B', 'Turno B'), ('Turno C', 'Turno C')], max_length=25, verbose_name='Turno')),
                ('local_trab', models.CharField(choices=[('Industria', 'Industria'), ('Frigorífico', 'Frigorífico'), ('Civil', 'Civil'), ('Indefinido', 'Indefinido'), ('ETE/ETA', 'ETE/ETA'), ('Utilidades', 'Utilidades'), ('Manutenção', 'Manutenção')], max_length=40, verbose_name='Local de Trabalho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Manutentor',
                'verbose_name_plural': 'Manutentores',
                'ordering': ['Nome', 'Cadastro'],
            },
        ),
    ]
