# Generated by Django 5.2.7 on 2025-11-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_manutentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.IntegerField(blank=True, null=True, verbose_name='Estante')),
                ('prateleira', models.IntegerField(blank=True, null=True, verbose_name='Prateleira')),
                ('coluna', models.IntegerField(blank=True, null=True, verbose_name='Coluna')),
                ('sequencia', models.IntegerField(blank=True, null=True, verbose_name='Sequência')),
                ('descricao_dest_uso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Destino Uso')),
                ('codigo_item', models.BigIntegerField(db_index=True, unique=True, verbose_name='Código Item')),
                ('descricao_item', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Item')),
                ('unidade_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade Medida')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('controla_estoque_minimo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Controla Estoque Mínimo')),
                ('classificacao_tempo_sem_consumo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classificação Tempo Sem Consumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['codigo_item'],
            },
        ),
    ]
