# Generated by Django 5.2.7 on 2025-11-09 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_itemestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoCsv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Manutenção CSV',
                'verbose_name_plural': 'Manutenções CSV',
            },
        ),
        migrations.CreateModel(
            name='ManutencaoTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('os', models.CharField(blank=True, max_length=150, null=True, verbose_name='OS')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('pedidodecompra', models.CharField(max_length=150, verbose_name='Pedido de Compra')),
                ('requisicaodecompra', models.CharField(max_length=150, verbose_name='Requisição de Compra')),
                ('tipo', models.CharField(choices=[('Corretiva', 'Corretiva'), ('Preventiva', 'Preventiva')], default='Corretiva', max_length=25, verbose_name='Tipo')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('manutentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manutentor', verbose_name='Manutentor')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maquina', verbose_name='Máquina')),
                ('os_importada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manutencaocsv', verbose_name='OS Importada')),
            ],
            options={
                'verbose_name': 'Manutenção Terceiro',
                'verbose_name_plural': 'Manutenções Terceiros',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
