# Generated by Django 5.2.7 on 2025-11-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_manutencaocsv_manutencaoterceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='Upload de arquivo PDF relacionado à máquina', null=True, upload_to='arquivos_maquinas/', verbose_name='Arquivo PDF'),
        ),
    ]
