# Generated by Django 5.2.7 on 2025-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_maquina_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='diagrama_eletrico',
            field=models.FileField(blank=True, help_text='Upload de arquivo PDF do diagrama elétrico', null=True, upload_to='arquivos_maquinas/', verbose_name='Diagrama Elétrico'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='pecas_reposicao',
            field=models.FileField(blank=True, help_text='Upload de arquivo PDF de peças de reposição', null=True, upload_to='arquivos_maquinas/', verbose_name='Peças de Reposição'),
        ),
    ]
