# Generated by Django 5.2.7 on 2025-11-10 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_maquina_diagrama_eletrico_maquina_pecas_reposicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, help_text='Quantidade necessária desta peça para a máquina', max_digits=15, verbose_name='Quantidade')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o uso desta peça na máquina', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='app.itemestoque', verbose_name='Item de Estoque')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='app.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Peça de Máquina',
                'verbose_name_plural': 'Peças de Máquinas',
                'ordering': ['-created_at'],
                'unique_together': {('maquina', 'item_estoque')},
            },
        ),
    ]
