# Generated by Django 5.2.7 on 2025-11-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_maquinapeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='codigo_aurora',
            field=models.ImageField(blank=True, help_text='Foto do código Aurora', null=True, upload_to='maquinas/codigos/', verbose_name='Código Aurora'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='codigo_fabricante',
            field=models.ImageField(blank=True, help_text='Foto do código do fabricante', null=True, upload_to='maquinas/codigos/', verbose_name='Código do Fabricante'),
        ),
    ]
