# Generated by Django 5.2.7 on 2025-11-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_maquina_codigo_aurora_maquina_codigo_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='documentacao_tecnica',
            field=models.FileField(blank=True, help_text='Documentação técnica em PDF', null=True, upload_to='estoque/documentacao/', verbose_name='Documentação Técnica'),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='foto_detalhada',
            field=models.ImageField(blank=True, help_text='Foto detalhada do item', null=True, upload_to='estoque/fotos_detalhadas/', verbose_name='Foto Detalhada'),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='foto_item',
            field=models.ImageField(blank=True, help_text='Foto do item de estoque', null=True, upload_to='estoque/fotos/', verbose_name='Foto do Item'),
        ),
    ]
