# Generated by Django 5.2.7 on 2025-11-11 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_itemestoque_documentacao_tecnica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutentorMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o relacionamento', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('manutentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='app.manutentor', verbose_name='Manutentor')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutentores', to='app.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Máquina do Manutentor',
                'verbose_name_plural': 'Máquinas dos Manutentores',
                'ordering': ['-created_at'],
                'unique_together': {('manutentor', 'maquina')},
            },
        ),
    ]
