# Generated by Django 5.2.7 on 2025-11-11 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_manutentormaquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservicocorretiva',
            name='cd_func_exec_os',
        ),
        migrations.RemoveField(
            model_name='ordemservicocorretiva',
            name='dt_ficapomanu',
        ),
        migrations.RemoveField(
            model_name='ordemservicocorretiva',
            name='dt_fim_iteficmanu',
        ),
        migrations.RemoveField(
            model_name='ordemservicocorretiva',
            name='dt_inic_iteficmanu',
        ),
        migrations.RemoveField(
            model_name='ordemservicocorretiva',
            name='nm_func_exec_os',
        ),
        migrations.CreateModel(
            name='OrdemServicoCorretivaFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_func_exec_os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Funcionário Executor OS')),
                ('nm_func_exec_os', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funcionário Executor OS')),
                ('dt_ficapomanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Ficha Ponto Manutenção')),
                ('dt_inic_iteficmanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Início Item Ficha Manutenção')),
                ('dt_fim_iteficmanu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Fim Item Ficha Manutenção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='app.ordemservicocorretiva', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Ficha de Manutenção',
                'verbose_name_plural': 'Fichas de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
    ]
