# Generated by Django 5.2.7 on 2025-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_migrate_ficha_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroatividade',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local'),
        ),
    ]
