# Generated by Django 5.2.7 on 2025-11-11 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_centroatividade_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaPrimariaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o relacionamento', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('maquina_primaria', models.ForeignKey(limit_choices_to={'descr_gerenc': 'MÁQUINAS PRINCIPAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='maquinas_secundarias', to='app.maquina', verbose_name='Máquina Primária')),
                ('maquina_secundaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas_primarias', to='app.maquina', verbose_name='Máquina Secundária')),
            ],
            options={
                'verbose_name': 'Máquina Primária e Secundária',
                'verbose_name_plural': 'Máquinas Primárias e Secundárias',
                'ordering': ['-created_at'],
                'unique_together': {('maquina_primaria', 'maquina_secundaria')},
            },
        ),
    ]
