# Generated by Django 5.2.7 on 2025-11-13 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_maquinaprimariasecundaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centroatividade',
            name='local',
        ),
        migrations.AlterField(
            model_name='maquinaprimariasecundaria',
            name='maquina_primaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas_secundarias', to='app.maquina', verbose_name='Máquina Primária'),
        ),
        migrations.CreateModel(
            name='LocalCentroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o local', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('centro_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='app.centroatividade', verbose_name='Centro de Atividade')),
            ],
            options={
                'verbose_name': 'Local do Centro de Atividade',
                'verbose_name_plural': 'Locais dos Centros de Atividade',
                'ordering': ['local'],
            },
        ),
    ]
