# Generated by Django 5.2.7 on 2025-11-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_centroatividade_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='local_centro_atividade',
            field=models.ForeignKey(blank=True, help_text='Local do Centro de Atividade relacionado ao setor de manutenção', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.localcentroatividade', verbose_name='Local do Centro de Atividade'),
        ),
    ]
