# Generated by Django 5.2.7 on 2025-11-15 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_maquina_local_centro_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaDocumentoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Upload de arquivo para manutenção preventiva (PDF, imagens, etc.)', upload_to='maquinas/documentos_preventiva/', verbose_name='Arquivo')),
                ('comentario', models.TextField(blank=True, help_text='Comentário sobre o documento', null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_preventiva', to='app.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Documento de Manutenção Preventiva',
                'verbose_name_plural': 'Documentos de Manutenção Preventiva',
                'ordering': ['-created_at'],
            },
        ),
    ]
