# Generated by Django 5.2.7 on 2025-11-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_maquinadocumentopreventiva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaquinaDocumentoPreventiva',
        ),
    ]
