# Generated by Django 5.2.7 on 2025-11-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_maquinadocumentopreventiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unid', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade')),
                ('nome_unid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('cd_setor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Setor')),
                ('descr_setor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Setor')),
                ('cd_atividade', models.IntegerField(blank=True, null=True, verbose_name='Código Atividade')),
                ('cd_maquina', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Código Máquina')),
                ('descr_maquina', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Máquina')),
                ('nro_patrimonio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Patrimônio')),
                ('numero_plano', models.IntegerField(blank=True, null=True, verbose_name='Número do Plano')),
                ('descr_plano', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Plano')),
                ('sequencia_manutencao', models.IntegerField(blank=True, null=True, verbose_name='Sequência Manutenção')),
                ('dt_execucao', models.CharField(blank=True, help_text='Data no formato DD/MM/YYYY', max_length=50, null=True, verbose_name='Data Execução')),
                ('quantidade_periodo', models.IntegerField(blank=True, help_text='Período em dias', null=True, verbose_name='Quantidade Período')),
                ('sequencia_tarefa', models.IntegerField(blank=True, null=True, verbose_name='Sequência Tarefa')),
                ('descr_tarefa', models.TextField(blank=True, null=True, verbose_name='Descrição Tarefa')),
                ('cd_funcionario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Funcionário')),
                ('nome_funcionario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funcionário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('maquina', models.ForeignKey(blank=True, help_text='Máquina relacionada baseada no código da máquina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_preventiva', to='app.maquina', verbose_name='Máquina Relacionada')),
            ],
            options={
                'verbose_name': 'Plano Preventiva',
                'verbose_name_plural': 'Planos Preventiva',
                'ordering': ['cd_maquina', 'numero_plano', 'sequencia_manutencao', 'sequencia_tarefa'],
                'indexes': [models.Index(fields=['cd_maquina'], name='app_planopr_cd_maqu_ecf556_idx'), models.Index(fields=['cd_unid', 'cd_setor'], name='app_planopr_cd_unid_c48185_idx')],
            },
        ),
    ]
