# Generated by Django 5.2.7 on 2025-11-15 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_planopreventiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoPreventivaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Upload de arquivo relacionado ao plano preventiva (PDF, imagens, etc.)', upload_to='planos_preventiva/documentos/', verbose_name='Arquivo')),
                ('comentario', models.TextField(blank=True, help_text='Comentário sobre o documento', null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('plano_preventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.planopreventiva', verbose_name='Plano Preventiva')),
            ],
            options={
                'verbose_name': 'Documento do Plano Preventiva',
                'verbose_name_plural': 'Documentos do Plano Preventiva',
                'ordering': ['-created_at'],
            },
        ),
    ]
