# Generated by Django 5.2.7 on 2025-11-15 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_planopreventivadocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoteiroPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unid', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade')),
                ('nome_unid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('cd_funciomanu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Funcionário Manutenção')),
                ('nome_funciomanu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funcionário Manutenção')),
                ('funciomanu_id', models.IntegerField(blank=True, null=True, verbose_name='ID Funcionário Manutenção')),
                ('cd_setormanut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Setor Manutenção')),
                ('descr_setormanut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Setor Manutenção')),
                ('cd_tpcentativ', models.IntegerField(blank=True, null=True, verbose_name='Código Tipo Centro Atividade')),
                ('descr_abrev_tpcentativ', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Abreviada Tipo Centro Atividade')),
                ('dt_abertura', models.CharField(blank=True, help_text='Data no formato DD/MM/YYYY', max_length=50, null=True, verbose_name='Data Abertura')),
                ('cd_ordemserv', models.IntegerField(blank=True, null=True, verbose_name='Código Ordem Serviço')),
                ('ordemserv_id', models.IntegerField(blank=True, null=True, verbose_name='ID Ordem Serviço')),
                ('cd_maquina', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Código Máquina')),
                ('descr_maquina', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Máquina')),
                ('cd_planmanut', models.IntegerField(blank=True, null=True, verbose_name='Código Plano Manutenção')),
                ('descr_planmanut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Plano Manutenção')),
                ('descr_recomenos', models.TextField(blank=True, null=True, verbose_name='Descrição Recomendações')),
                ('cf_dt_final_execucao', models.CharField(blank=True, help_text='Data no formato DD/MM/YYYY', max_length=50, null=True, verbose_name='Data Final Execução')),
                ('cs_qtde_periodo_max', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Período Máximo')),
                ('cs_tot_temp', models.CharField(blank=True, help_text='Tempo no formato HH:MM', max_length=50, null=True, verbose_name='Total Tempo (Calculado)')),
                ('cf_tot_temp', models.CharField(blank=True, help_text='Tempo no formato HH:MM', max_length=50, null=True, verbose_name='Total Tempo (Final)')),
                ('seq_seqplamanu', models.IntegerField(blank=True, null=True, verbose_name='Sequência Plano Manutenção')),
                ('cd_tarefamanu', models.IntegerField(blank=True, null=True, verbose_name='Código Tarefa Manutenção')),
                ('descr_tarefamanu', models.TextField(blank=True, null=True, verbose_name='Descrição Tarefa Manutenção')),
                ('descr_periodo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Período')),
                ('dt_primexec', models.CharField(blank=True, help_text='Data no formato DD/MM/YYYY', max_length=50, null=True, verbose_name='Data Primeira Execução')),
                ('tempo_prev', models.CharField(blank=True, help_text='Tempo no formato HH:MM', max_length=50, null=True, verbose_name='Tempo Preventivo')),
                ('qtde_periodo', models.IntegerField(blank=True, help_text='Período em dias', null=True, verbose_name='Quantidade Período')),
                ('descr_seqplamanu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Sequência Plano Manutenção')),
                ('cf_temp_prev', models.CharField(blank=True, help_text='Tempo no formato HH:MM', max_length=50, null=True, verbose_name='Tempo Preventivo (Final)')),
                ('itemplanma_id', models.IntegerField(blank=True, null=True, verbose_name='ID Item Plano Manutenção')),
                ('cd_item', models.IntegerField(blank=True, null=True, verbose_name='Código Item')),
                ('descr_item', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Item')),
                ('item_id', models.IntegerField(blank=True, null=True, verbose_name='ID Item')),
                ('qtde', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('qtde_saldo', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Saldo')),
                ('qtde_reserva', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('maquina', models.ForeignKey(blank=True, help_text='Máquina relacionada baseada no código da máquina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_preventiva', to='app.maquina', verbose_name='Máquina Relacionada')),
            ],
            options={
                'verbose_name': 'Roteiro Preventiva',
                'verbose_name_plural': 'Roteiros Preventiva',
                'ordering': ['cd_maquina', 'cd_planmanut', 'seq_seqplamanu', 'cd_tarefamanu'],
                'indexes': [models.Index(fields=['cd_maquina'], name='app_roteiro_cd_maqu_d38448_idx'), models.Index(fields=['cd_unid', 'cd_setormanut'], name='app_roteiro_cd_unid_cb5cfb_idx'), models.Index(fields=['cd_ordemserv'], name='app_roteiro_cd_orde_6967e3_idx'), models.Index(fields=['cd_planmanut'], name='app_roteiro_cd_plan_d4264c_idx')],
            },
        ),
    ]
