# Generated by Django 5.2.7 on 2025-11-16 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_roteiropreventiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='planopreventiva',
            name='descr_seqplamanu',
            field=models.CharField(blank=True, help_text='Descrição precisa da ação a ser realizada, vinculada do RoteiroPreventiva', max_length=255, null=True, verbose_name='Descrição Sequência Plano Manutenção'),
        ),
        migrations.AddField(
            model_name='planopreventiva',
            name='roteiro_preventiva',
            field=models.ForeignKey(blank=True, help_text='Roteiro preventiva relacionado que contém a descrição precisa (DESCR_SEQPLAMANU)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_preventiva', to='app.roteiropreventiva', verbose_name='Roteiro Preventiva Relacionado'),
        ),
    ]
