# Generated by Django 5.2.7 on 2025-11-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_meuplanopreventiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Upload de arquivo relacionado à máquina (PDF, imagens, etc.)', upload_to='maquinas/documentos/', verbose_name='Arquivo')),
                ('comentario', models.TextField(blank=True, help_text='Comentário sobre o documento', null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Documento da Máquina',
                'verbose_name_plural': 'Documentos da Máquina',
                'ordering': ['-created_at'],
            },
        ),
    ]
