# Generated by Django 5.2.7 on 2025-11-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_maquinadocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuPlanoPreventivaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, help_text='Comentário adicional sobre esta associação (opcional)', null=True, verbose_name='Comentário Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('maquina_documento', models.ForeignKey(help_text='Documento da máquina associado a este plano', on_delete=django.db.models.deletion.CASCADE, related_name='meus_planos_preventiva_associados', to='app.maquinadocumento', verbose_name='Documento da Máquina')),
                ('meu_plano_preventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_associados', to='app.meuplanopreventiva', verbose_name='Meu Plano Preventiva')),
            ],
            options={
                'verbose_name': 'Documento Associado ao Plano PCM',
                'verbose_name_plural': 'Documentos Associados aos Planos PCM',
                'ordering': ['-created_at'],
                'unique_together': {('meu_plano_preventiva', 'maquina_documento')},
            },
        ),
    ]
