# Generated by Django 5.2.7 on 2025-11-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_meuplanopreventivadocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semana52',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Semana')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Semana 52',
                'verbose_name_plural': 'Semanas 52',
                'ordering': ['inicio'],
            },
        ),
    ]
