# Generated by Django 5.2.7 on 2025-12-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_semana52'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_agendamento', models.CharField(choices=[('maquina', 'Máquina'), ('plano', 'Plano Preventiva')], help_text='Tipo de item agendado: Máquina ou Plano Preventiva', max_length=10, verbose_name='Tipo de Agendamento')),
                ('data_planejada', models.DateField(help_text='Data planejada para execução do agendamento', verbose_name='Data Planejada')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre este agendamento', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by', models.CharField(blank=True, help_text='Usuário que criou o agendamento', max_length=255, null=True, verbose_name='Criado por')),
                ('maquina', models.ForeignKey(blank=True, help_text='Máquina agendada (usado quando tipo_agendamento = "maquina")', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cronograma', to='app.maquina', verbose_name='Máquina')),
                ('plano_preventiva', models.ForeignKey(blank=True, help_text='Plano Preventiva agendado (usado quando tipo_agendamento = "plano")', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cronograma', to='app.meuplanopreventiva', verbose_name='Plano Preventiva')),
                ('semana', models.ForeignKey(blank=True, help_text='Semana do ano relacionada (calculada automaticamente baseada na data_planejada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='app.semana52', verbose_name='Semana')),
            ],
            options={
                'verbose_name': 'Agendamento de Cronograma',
                'verbose_name_plural': 'Agendamentos de Cronograma',
                'ordering': ['data_planejada', 'tipo_agendamento'],
                'indexes': [models.Index(fields=['data_planejada'], name='app_agendam_data_pl_f269db_idx'), models.Index(fields=['tipo_agendamento'], name='app_agendam_tipo_ag_d06dd7_idx'), models.Index(fields=['maquina'], name='app_agendam_maquina_9d202b_idx'), models.Index(fields=['plano_preventiva'], name='app_agendam_plano_p_cb7ff5_idx')],
            },
        ),
    ]
