# Generated by Django 5.2.7 on 2025-12-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_agendamentocronograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentocronograma',
            name='nome_grupo',
            field=models.CharField(blank=True, help_text='Nome identificador para este grupo de agendamentos (ex: "Manutenção Preventiva - Setor A")', max_length=255, null=True, verbose_name='Nome do Grupo'),
        ),
        migrations.AddField(
            model_name='agendamentocronograma',
            name='periodicidade',
            field=models.IntegerField(blank=True, help_text='Número de dias entre cada repetição do agendamento até o final do ano', null=True, verbose_name='Periodicidade (dias)'),
        ),
    ]
