# Generated by Django 5.2.7 on 2025-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_agendamentocronograma_nome_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisicao', models.DateField(help_text='Data em que os itens foram retirados do estoque', verbose_name='Data da Requisição')),
                ('cd_unid', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade')),
                ('nome_unid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('cd_uso_ctb', models.IntegerField(blank=True, null=True, verbose_name='Código Uso Contábil')),
                ('descr_uso_ctb', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Uso Contábil')),
                ('cd_depo', models.IntegerField(blank=True, null=True, verbose_name='Código Depósito')),
                ('descr_depo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Depósito')),
                ('cd_local_fisic', models.IntegerField(blank=True, null=True, verbose_name='Código Local Físico')),
                ('descr_local_fisic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Local Físico')),
                ('cd_item', models.BigIntegerField(db_index=True, verbose_name='Código Item')),
                ('cd_embalagem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Embalagem')),
                ('descr_item', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Item')),
                ('cd_operacao', models.IntegerField(blank=True, null=True, verbose_name='Código Operação')),
                ('descr_operacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Operação')),
                ('cd_unid_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Unidade Medida')),
                ('qtde_movto_estoq', models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade movimentada (geralmente negativa para saída)', max_digits=15, null=True, verbose_name='Quantidade Movimento Estoque')),
                ('vlr_movto_estoq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Movimento Estoque')),
                ('vlr_movto_estoq_reav', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Movimento Estoque Reavaliação')),
                ('cd_unid_baixa', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade Baixa')),
                ('cd_centro_ativ', models.IntegerField(blank=True, null=True, verbose_name='Código Centro Atividade')),
                ('cd_usu_criou', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Usuário Criou')),
                ('cd_usu_atend', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Usuário Atendeu')),
                ('obs_rm', models.TextField(blank=True, null=True, verbose_name='Observação RM')),
                ('obs_item', models.TextField(blank=True, null=True, verbose_name='Observação Item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Requisição Almoxarifado',
                'verbose_name_plural': 'Requisições Almoxarifado',
                'ordering': ['-data_requisicao', '-created_at'],
                'indexes': [models.Index(fields=['data_requisicao'], name='app_requisi_data_re_d654ab_idx'), models.Index(fields=['cd_item'], name='app_requisi_cd_item_d3709c_idx'), models.Index(fields=['cd_centro_ativ'], name='app_requisi_cd_cent_fa25cf_idx')],
            },
        ),
    ]
