# Generated by Django 5.2.7 on 2025-12-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20251204_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutentor',
            options={'ordering': ['Nome', 'Matricula'], 'verbose_name': 'Manutentor', 'verbose_name_plural': 'Manutentores'},
        ),
        migrations.RemoveField(
            model_name='manutentor',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='manutentor',
            name='Matricula',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
    ]
