# Generated by Django 5.2.7 on 2025-12-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_manutentor_options_remove_manutentor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana52',
            name='inicio',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='semana52',
            name='semana',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Semana'),
        ),
        migrations.AlterUniqueTogether(
            name='semana52',
            unique_together={('semana', 'inicio')},
        ),
    ]
