# Generated by Django 5.2.7 on 2025-12-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_unique_semana_add_composite_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitente', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Emitente (CNPJ)')),
                ('nome_fantasia_emitente', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome Fantasia Emitente')),
                ('nota', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Número da Nota')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Série')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('total_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total da Nota')),
                ('data_emissao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Emissão')),
                ('data_vencimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Vencimento')),
                ('data_inclusao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Inclusão')),
                ('data_autorizacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Autorização')),
                ('data_ult_sit_fechada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Última Situação Fechada')),
                ('ctrle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Controle')),
                ('unidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade')),
                ('nome_unidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('unidade_autorizacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade Autorização')),
                ('nome_unidade_autorizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade Autorização')),
                ('centro_atividade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro Atividade')),
                ('nome_centro_atividade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Centro Atividade')),
                ('situacao', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Situação')),
                ('situacao_detalhada', models.TextField(blank=True, null=True, verbose_name='Situação Detalhada')),
                ('nome_usuario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Usuário')),
                ('autorizador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autorizador')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('observacoes_csc', models.TextField(blank=True, null=True, verbose_name='Observações CSC')),
                ('observacoes_autorizacao', models.TextField(blank=True, null=True, verbose_name='Observações Autorização')),
                ('lancamento_tesf0028', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lançamento TESF0028')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao', '-created_at'],
                'indexes': [models.Index(fields=['situacao'], name='app_notafis_situaca_50bfa2_idx'), models.Index(fields=['data_emissao'], name='app_notafis_data_em_f7a8fb_idx'), models.Index(fields=['unidade'], name='app_notafis_unidade_e82310_idx')],
                'unique_together': {('emitente', 'nota', 'serie', 'modelo')},
            },
        ),
    ]
