# Generated by Django 5.2.7 on 2025-12-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_add_nota_fiscal_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição')),
                ('nome_contato', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do Contato')),
                ('numero_contato', models.CharField(blank=True, max_length=250, null=True, verbose_name='Número do Contato')),
                ('documento', models.FileField(blank=True, default='evento/padrao/foto_padrao.jpg', null=True, upload_to='evento/documento/', verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('agendamento', models.ForeignKey(blank=True, help_text='Agendamento relacionado a esta visita', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='app.agendamentocronograma', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data', '-created_at'],
                'indexes': [models.Index(fields=['data'], name='app_visitas_data_762861_idx'), models.Index(fields=['titulo'], name='app_visitas_titulo_b37261_idx')],
            },
        ),
    ]
