# Generated by Django 5.2.7 on 2025-12-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_visitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitas',
            name='agendamento',
        ),
    ]
