# Generated by Django 5.2.7 on 2025-12-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_visitas_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='evento/documento/', verbose_name='Documento'),
        ),
    ]
