# Generated by Django 5.2.7 on 2025-12-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_visitas_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='centro_de_custo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de Custo'),
        ),
    ]
