# Generated by Django 5.2.7 on 2025-12-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_notafiscal_centro_de_custo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notafiscal',
            old_name='centro_de_custo',
            new_name='uso_contabil',
        ),
    ]


