# Generated by Django 5.2.7 on 2025-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_centro_de_custo_to_uso_contabil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='uso_contabil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uso Contábil'),
        ),
        migrations.CreateModel(
            name='ProjecaoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('centro_atividade', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Centro de Atividade')),
                ('nome_centro_atividade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Centro de Atividade')),
                ('valor_planejado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Planejado')),
                ('valor_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Realizado')),
                ('valor_projetado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Projetado')),
                ('data_requisicao', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Requisição')),
                ('data_planejada', models.DateField(blank=True, null=True, verbose_name='Data Planejada')),
                ('data_realizada', models.DateField(blank=True, null=True, verbose_name='Data Realizada')),
                ('mes_referencia', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Mês Referência')),
                ('ano_referencia', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Ano Referência')),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor')),
                ('numero_requisicao', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número Requisição')),
                ('numero_ordem_servico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Ordem de Serviço')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dados_adicionais', models.JSONField(blank=True, default=dict, null=True, verbose_name='Dados Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Projeção de Gasto',
                'verbose_name_plural': 'Projeções de Gastos',
                'ordering': ['-ano_referencia', '-mes_referencia', '-data_requisicao', '-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='app_projeca_tipo_afa197_idx'), models.Index(fields=['centro_atividade'], name='app_projeca_centro__52c2bd_idx'), models.Index(fields=['mes_referencia', 'ano_referencia'], name='app_projeca_mes_ref_3cd4d5_idx'), models.Index(fields=['data_requisicao'], name='app_projeca_data_re_201173_idx')],
            },
        ),
    ]
