# Generated by Django 5.2.7 on 2025-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_notafiscal_uso_contabil_projecaogasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecaogasto',
            options={'ordering': ['-ano_referencia', '-mes_referencia', '-data_abertura_requisicao', '-created_at'], 'verbose_name': 'Projeção de Gasto', 'verbose_name_plural': 'Projeções de Gastos'},
        ),
        migrations.RemoveIndex(
            model_name='projecaogasto',
            name='app_projeca_data_re_201173_idx',
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='data_abertura_requisicao',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Abertura da Requisição'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='fornecedor_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fornecedor CNPJ'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='fornecedor_nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='nf_enviada_lancamento',
            field=models.DateField(blank=True, null=True, verbose_name='NF Enviada para Lançamento'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='nf_servico_recebida',
            field=models.DateField(blank=True, null=True, verbose_name='NF de Serviço Recebida'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='numero_nf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da NF'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='numero_pedido_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Pedido de Compra'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='numero_requisicao_compra',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número da Requisição de Compra'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='previsao_execucao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Previsão para Execução'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='servico_concluido',
            field=models.DateField(blank=True, null=True, verbose_name='Serviço Concluído'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='setor',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='uso_contabil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uso Contábil'),
        ),
        migrations.AddField(
            model_name='projecaogasto',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='projecaogasto',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='projecaogasto',
            name='numero_ordem_servico',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número Ordem de Serviço'),
        ),
        migrations.AddIndex(
            model_name='projecaogasto',
            index=models.Index(fields=['setor'], name='app_projeca_setor_0fac41_idx'),
        ),
        migrations.AddIndex(
            model_name='projecaogasto',
            index=models.Index(fields=['data_abertura_requisicao'], name='app_projeca_data_ab_51f77a_idx'),
        ),
        migrations.AddIndex(
            model_name='projecaogasto',
            index=models.Index(fields=['numero_requisicao_compra'], name='app_projeca_numero__0dc2d2_idx'),
        ),
    ]
