# Generated by Django 6.0 on 2025-12-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_ajuste_projecao_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoProjecaoNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_match', models.DecimalField(blank=True, decimal_places=2, help_text='Score percentual do match quando foi confirmado', max_digits=5, null=True, verbose_name='Score do Match')),
                ('confirmado_por', models.CharField(blank=True, help_text='Usuário que confirmou a relação', max_length=255, null=True, verbose_name='Confirmado por')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a relação confirmada', null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado'), ('pendente', 'Pendente')], db_index=True, default='confirmado', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_projecoes', to='app.notafiscal', verbose_name='Nota Fiscal')),
                ('projecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_notas_fiscais', to='app.projecaogasto', verbose_name='Projeção de Gasto')),
            ],
            options={
                'verbose_name': 'Relação Projeção vs Nota Fiscal',
                'verbose_name_plural': 'Relações Projeção vs Nota Fiscal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='app_relacao_status_2fddfa_idx'), models.Index(fields=['projecao'], name='app_relacao_projeca_017520_idx'), models.Index(fields=['nota_fiscal'], name='app_relacao_nota_fi_fb2516_idx'), models.Index(fields=['created_at'], name='app_relacao_created_59e7b7_idx')],
                'unique_together': {('projecao', 'nota_fiscal')},
            },
        ),
    ]
