# Generated by Django 6.0 on 2025-12-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_relacaoprojecaonotafiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês')),
                ('conta_orcamentaria', models.CharField(max_length=255, verbose_name='Conta Orçamentária')),
                ('valor_orcamento', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Orçamento')),
                ('valor_final_desejado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Final Desejado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Dado de Orçamento',
                'verbose_name_plural': 'Dados de Orçamento',
                'ordering': ['ano', 'mes', 'conta_orcamentaria'],
                'indexes': [models.Index(fields=['ano', 'mes'], name='app_dadosor_ano_506657_idx'), models.Index(fields=['conta_orcamentaria'], name='app_dadosor_conta_o_f8a130_idx')],
                'unique_together': {('ano', 'mes', 'conta_orcamentaria')},
            },
        ),
    ]
