# Generated by Django 5.2.7 on 2025-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_merge_local_centro_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoalmoxarifado',
            name='dia',
            field=models.DateField(blank=True, help_text='Data extraída da coluna DIA do arquivo CSV', null=True, verbose_name='Dia'),
        ),
    ]
