# Generated by Django 5.2.7 on 2025-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_add_dia_field_to_requisicao_almoxarifado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaoalmoxarifado',
            name='dia',
        ),
        migrations.AddField(
            model_name='centroatividade',
            name='imagem',
            field=models.CharField(blank=True, help_text='Caminho da imagem (relativo a static/)', max_length=500, null=True, verbose_name='Imagem'),
        ),
    ]
