# Generated by Django 5.2.7 on 2025-12-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_add_imagem_to_centroatividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroatividade',
            name='ca',
            field=models.IntegerField(db_index=True, verbose_name='CA'),
        ),
    ]
