# Generated by Django 5.2.7 on 2025-12-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_unique_constraint_from_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se a máquina está ativa no sistema', verbose_name='Ativo'),
        ),
        migrations.AddIndex(
            model_name='maquina',
            index=models.Index(fields=['ativo', 'cd_maquina'], name='app_maquina_ativo_b5bd4a_idx'),
        ),
    ]
