# Generated by Django 6.0 on 2025-12-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_controlercenf'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='controlercenf',
            name='app_control_nf_said_c0268b_idx',
        ),
        migrations.RemoveIndex(
            model_name='controlercenf',
            name='app_control_rc_3384df_idx',
        ),
        migrations.RemoveIndex(
            model_name='controlercenf',
            name='app_control_pedido_8e8b2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='controlercenf',
            name='app_control_data_rc_80dd97_idx',
        ),
        migrations.DeleteModel(
            name='ControleRCeNF',
        ),
        migrations.RemoveIndex(
            model_name='maquina',
            name='app_maquina_ativo_b5bd4a_idx',
        ),
        migrations.RemoveField(
            model_name='centroatividade',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='centroatividade',
            name='ca',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='CA'),
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='ativo',
        ),
    ]
