# Generated by Django 5.2.7 on 2025-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_controlercenf_app_control_nf_said_c0268b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleRCeNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitante')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('nf_saida', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='NF Saída')),
                ('descricao_servico', models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço')),
                ('ca_rateio', models.CharField(blank=True, max_length=100, null=True, verbose_name='C.A/Rateio')),
                ('uso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uso')),
                ('quem_abriu_rc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quem Abriu a RC')),
                ('orcamento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Orçamento')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='O.S')),
                ('classificacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Classificação')),
                ('justificativa_classificacao', models.TextField(blank=True, null=True, verbose_name='Justificativa Classificação')),
                ('spaf0009_acesso_portaria', models.CharField(blank=True, max_length=255, null=True, verbose_name='SPAF0009 - Acesso portaria p/ classif. 5 e 8')),
                ('rc', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='RC')),
                ('data_rc', models.DateTimeField(blank=True, null=True, verbose_name='Data RC')),
                ('pedido', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Pedido')),
                ('valor_total_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total do Pedido')),
                ('previsao_para_uso', models.DateTimeField(blank=True, null=True, verbose_name='Previsão para Uso')),
                ('nf_servico', models.CharField(blank=True, max_length=100, null=True, verbose_name='NF Serviço')),
                ('nf_retorno_e_data_lancamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='NF Retorno e Data Lançamento')),
                ('cnpj_aurora', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ Aurora')),
                ('simples_nacional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Simples Nacional')),
                ('valor_nf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor NF')),
                ('emissao', models.DateTimeField(blank=True, null=True, verbose_name='Emissão')),
                ('inclusao_198', models.DateTimeField(blank=True, null=True, verbose_name='Inclusão 198')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('saldo_residual_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Residual Pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Controle RC e NF',
                'verbose_name_plural': 'Controles RC e NF',
                'ordering': ['-data_rc', '-created_at'],
                'indexes': [models.Index(fields=['nf_saida'], name='app_control_nf_said_c0268b_idx'), models.Index(fields=['rc'], name='app_control_rc_3384df_idx'), models.Index(fields=['pedido'], name='app_control_pedido_8e8b2e_idx'), models.Index(fields=['data_rc'], name='app_control_data_rc_80dd97_idx')],
            },
        ),
    ]
