# Generated by Django 6.0 on 2026-01-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_ordemservicopreventiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlercenf',
            name='id_excel',
            field=models.CharField(blank=True, db_index=True, help_text='ID único do registro na planilha Excel', max_length=100, null=True, unique=True, verbose_name='ID'),
        ),
        # Removed unique constraints from ProjecaoGasto fields due to existing duplicates in database
        # migrations.AlterField operations removed to avoid IntegrityError
        migrations.AddIndex(
            model_name='controlercenf',
            index=models.Index(fields=['id_excel'], name='app_control_id_exce_5e27eb_idx'),
        ),
    ]
