# Generated by Django 6.0 on 2026-01-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_add_id_excel_to_controle_rc_e_nf'),
    ]

    operations = [
        # Removed unique constraints from ProjecaoGasto fields due to existing duplicates in database
        migrations.CreateModel(
            name='SaldoOrcamentarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_index=True, verbose_name='Mês')),
                ('conta_orcamentaria', models.CharField(db_index=True, max_length=255, verbose_name='Conta Orçamentária')),
                ('saldo_orcamentario_desejado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Orçamentário Desejado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_orcamentarios', to='app.semana52', verbose_name='Semana')),
            ],
            options={
                'verbose_name': 'Saldo Orçamentário Semanal',
                'verbose_name_plural': 'Saldos Orçamentários Semanais',
                'ordering': ['ano', 'mes', 'conta_orcamentaria', 'semana__inicio'],
                'indexes': [models.Index(fields=['ano', 'mes', 'conta_orcamentaria'], name='app_saldoor_ano_565fc3_idx'), models.Index(fields=['semana'], name='app_saldoor_semana__0cb398_idx')],
                'unique_together': {('ano', 'mes', 'conta_orcamentaria', 'semana')},
            },
        ),
    ]
