# Generated by Django 5.2.7 on 2026-01-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_add_saldo_orcamentario_semanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecaogasto',
            name='numero_pedido_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Pedido de Compra'),
        ),
        migrations.AlterField(
            model_name='projecaogasto',
            name='numero_requisicao_compra',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número da Requisição de Compra'),
        ),
        migrations.CreateModel(
            name='ParadaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.IntegerField(blank=True, null=True, verbose_name='Unidade')),
                ('nome_unidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('linha_producao', models.IntegerField(blank=True, null=True, verbose_name='Linha de Produção')),
                ('descr_linha_producao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Linha de Produção')),
                ('turno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Turno')),
                ('data', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data')),
                ('cod_item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Item')),
                ('descr_item', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Item')),
                ('cod_grupo_recurso', models.IntegerField(blank=True, null=True, verbose_name='Código Grupo de Recurso')),
                ('grupo_recurso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Recurso')),
                ('cod_parada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Parada')),
                ('descr_parada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Parada')),
                ('nro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('cod_recurso', models.IntegerField(blank=True, null=True, verbose_name='Código Recurso')),
                ('descr_recurso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Recurso')),
                ('horario_inicial', models.TimeField(blank=True, null=True, verbose_name='Horário Inicial')),
                ('horario_final', models.TimeField(blank=True, null=True, verbose_name='Horário Final')),
                ('dif_hora', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Diferença Hora')),
                ('capacidade', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Capacidade')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('acao', models.TextField(blank=True, null=True, verbose_name='Ação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Parada de Máquina',
                'verbose_name_plural': 'Paradas de Máquinas',
                'ordering': ['-data', '-horario_inicial'],
                'indexes': [models.Index(fields=['data'], name='app_paradam_data_e0ceec_idx'), models.Index(fields=['cod_recurso'], name='app_paradam_cod_rec_e018df_idx'), models.Index(fields=['linha_producao'], name='app_paradam_linha_p_95919a_idx')],
            },
        ),
    ]
