# Generated by Django 5.2.7 on 2026-01-19 17:46

from django.db import migrations, models


def populate_id_excel(apps, schema_editor):
    """Populate id_excel with existing id values as temporary measure"""
    ProjecaoGasto = apps.get_model('app', 'ProjecaoGasto')
    for obj in ProjecaoGasto.objects.all():
        obj.id_excel = obj.id
        obj.save()


def reverse_populate_id_excel(apps, schema_editor):
    """Reverse migration - no-op"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_projecaogasto_numero_pedido_compra_and_more'),
    ]

    operations = [
        # Step 1: Remove unique constraints first (to avoid conflicts)
        migrations.AlterField(
            model_name='projecaogasto',
            name='numero_requisicao_compra',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número da Requisição de Compra'),
        ),
        migrations.AlterField(
            model_name='projecaogasto',
            name='numero_pedido_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Pedido de Compra'),
        ),
        # Step 2: Add id_excel as nullable field
        migrations.AddField(
            model_name='projecaogasto',
            name='id_excel',
            field=models.IntegerField(db_index=True, null=True, unique=True, verbose_name='ID Excel'),
        ),
        # Step 3: Add tipo_solicitacao field
        migrations.AddField(
            model_name='projecaogasto',
            name='tipo_solicitacao',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Tipo de Solicitação'),
        ),
        # Step 4: Populate id_excel with existing id values
        migrations.RunPython(populate_id_excel, reverse_populate_id_excel),
        # Step 5: Make id_excel non-nullable
        migrations.AlterField(
            model_name='projecaogasto',
            name='id_excel',
            field=models.IntegerField(db_index=True, null=False, unique=True, verbose_name='ID Excel'),
        ),
    ]
