# Generated by Django 6.0 on 2026-01-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_projecao_gasto_id_excel_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecaogasto',
            name='id_excel',
            field=models.IntegerField(db_index=True, verbose_name='ID Excel'),
        ),
        migrations.AlterField(
            model_name='projecaogasto',
            name='numero_pedido_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Pedido de Compra'),
        ),
        migrations.AlterField(
            model_name='projecaogasto',
            name='numero_requisicao_compra',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número da Requisição de Compra'),
        ),
        migrations.AlterUniqueTogether(
            name='projecaogasto',
            unique_together={('id_excel', 'setor')},
        ),
        migrations.AddIndex(
            model_name='projecaogasto',
            index=models.Index(fields=['id_excel', 'setor'], name='app_projeca_id_exce_b23294_idx'),
        ),
    ]
