# Generated by Django 6.0 on 2026-01-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_change_controle_rc_e_nf_id_excel_to_primary_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='controlercenf',
            name='app_control_id_exce_5e27eb_idx',
        ),
    ]
