# Generated by Django 6.0 on 2026-01-26 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_remove_controlercenf_app_control_id_exce_5e27eb_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relacaoprojecaonotafiscal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='relacaoprojecaonotafiscal',
            name='controle_rc_nf',
            field=models.ForeignKey(blank=True, help_text='Registro do Controle RC e NF relacionado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_projecoes_notas', to='app.controlercenf', verbose_name='Controle RC e NF'),
        ),
        migrations.AlterUniqueTogether(
            name='relacaoprojecaonotafiscal',
            unique_together={('projecao', 'nota_fiscal', 'controle_rc_nf')},
        ),
    ]
