# Generated by Django 5.2.7 on 2026-01-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_add_controle_rc_nf_to_relacao_projecao_nota_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParadaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mês')),
                ('secao', models.CharField(choices=[('frigorifico', 'Frigorífico'), ('industria', 'Indústria')], max_length=20, verbose_name='Seção')),
                ('suinos_abatidos', models.IntegerField(blank=True, null=True, verbose_name='Suínos Abatidos')),
                ('dias_uteis', models.IntegerField(blank=True, null=True, verbose_name='Dias úteis')),
                ('total_abate_planejado', models.IntegerField(blank=True, null=True, verbose_name='Total de Abate Planejado')),
                ('perda_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='% de Perda Máximo')),
                ('carcacas_por_minuto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nº Carcaças por Minuto')),
                ('industria_param1', models.IntegerField(blank=True, null=True, verbose_name='Indústria Parâmetro 1')),
                ('industria_param2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Indústria Parâmetro 2')),
                ('industria_param3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indústria Parâmetro 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração Parada de Máquina',
                'verbose_name_plural': 'Configurações Paradas de Máquina',
                'ordering': ['ano', 'mes', 'secao'],
            },
        ),
        migrations.AddIndex(
            model_name='relacaoprojecaonotafiscal',
            index=models.Index(fields=['controle_rc_nf'], name='app_relacao_control_e0a753_idx'),
        ),
        migrations.AddIndex(
            model_name='configparadamaquina',
            index=models.Index(fields=['ano', 'mes'], name='app_configp_ano_8f4e2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='configparadamaquina',
            constraint=models.UniqueConstraint(fields=('ano', 'mes', 'secao'), name='unique_config_parada_ano_mes_secao'),
        ),
    ]
