# Generated by Django 5.2.7 on 2026-01-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_config_parada_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRecursoParadaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('frigorifico', 'Frigorífico'), ('industria', 'Indústria')], max_length=20, verbose_name='Seção')),
                ('grupo_recurso', models.CharField(max_length=255, verbose_name='Grupo Recurso')),
            ],
            options={
                'verbose_name': 'Recurso incluído na Análise de Paradas',
                'verbose_name_plural': 'Recursos incluídos na Análise de Paradas',
                'ordering': ['secao', 'grupo_recurso'],
            },
        ),
        migrations.AddConstraint(
            model_name='paradamaquina',
            constraint=models.UniqueConstraint(fields=('data', 'cod_recurso', 'horario_inicial'), name='unique_parada_data_recurso_horario'),
        ),
        migrations.AddIndex(
            model_name='configrecursoparadamaquina',
            index=models.Index(fields=['secao'], name='app_configr_secao_876e99_idx'),
        ),
        migrations.AddConstraint(
            model_name='configrecursoparadamaquina',
            constraint=models.UniqueConstraint(fields=('secao', 'grupo_recurso'), name='unique_config_recurso_parada_secao_grupo'),
        ),
    ]
