# Generated by Django 5.2.7 on 2026-01-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_config_recurso_parada_back_to_descr_recurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configrecursoparadamaquina',
            options={'ordering': ['secao', 'descr_recurso'], 'verbose_name': 'Recurso incluído na Análise de Paradas', 'verbose_name_plural': 'Recursos incluídos na Análise de Paradas'},
        ),
        migrations.AlterField(
            model_name='configrecursoparadamaquina',
            name='descr_recurso',
            field=models.CharField(max_length=255, verbose_name='Descrição Recurso'),
        ),
        migrations.CreateModel(
            name='ProducaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mês')),
                ('dia', models.IntegerField(help_text='Dia do mês (1-31)', verbose_name='Dia')),
                ('suinos_abatidos', models.IntegerField(blank=True, null=True, verbose_name='Suínos Abatidos')),
                ('producao_industria', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Produção Indústria')),
            ],
            options={
                'verbose_name': 'Produção Diária',
                'verbose_name_plural': 'Produções Diárias',
                'ordering': ['ano', 'mes', 'dia'],
                'indexes': [models.Index(fields=['ano', 'mes'], name='app_produca_ano_05b0bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('ano', 'mes', 'dia'), name='unique_producao_diaria_ano_mes_dia')],
            },
        ),
    ]
