# Generated by Django 5.2.7 on 2026-02-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_config_parada_maquina_fator_eficiencia_industria'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projecaogasto',
            name='app_projeca_tipo_afa197_idx',
        ),
        migrations.RemoveIndex(
            model_name='projecaogasto',
            name='app_projeca_centro__52c2bd_idx',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='centro_atividade',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='data_planejada',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='data_realizada',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='data_requisicao',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='nome_centro_atividade',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='numero_requisicao',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='valor_planejado',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='valor_projetado',
        ),
        migrations.RemoveField(
            model_name='projecaogasto',
            name='valor_realizado',
        ),
        migrations.AddField(
            model_name='maquina',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Máquina ativa (exibir em listagens)', verbose_name='Ativo'),
        ),
    ]
