# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_remove_projecao_gasto_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecaogasto',
            name='excel_servico_concluido',
            field=models.DateField(blank=True, help_text='Importado diretamente da coluna SERVIÇO CONCLUÍDO do Excel', null=True, verbose_name='SERVIÇO CONCLUÍDO (Excel)'),
        ),
    ]
