# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_projecaogasto_excel_servico_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecaogasto',
            name='excel_servico_concluido',
            field=models.CharField(blank=True, help_text='Texto da coluna SERVIÇO CONCLUÍDO do Excel (não é data)', max_length=255, null=True, verbose_name='SERVIÇO CONCLUÍDO (Excel)'),
        ),
    ]
