# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_alter_projecaogasto_excel_servico_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecaogasto',
            name='nf_servico_recebida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NF de Serviço Recebida'),
        ),
        migrations.AlterField(
            model_name='projecaogasto',
            name='nf_enviada_lancamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NF Enviada para Lançamento'),
        ),
    ]
