# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_projecaogasto_nf_fields_to_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecaogasto',
            name='servico_concluido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serviço Concluído'),
        ),
    ]
