# Generated by Django 5.2.7 on 2026-02-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_alter_projecaogasto_servico_concluido_to_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecaogasto',
            name='excel_servico_concluido',
        ),
    ]
