# Generated by Django 5.2.7 on 2026-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_config_linha_producao_centro_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
                ('arquivo', models.FileField(blank=True, help_text='Upload de arquivo relacionado ao evento', null=True, upload_to='eventos/arquivos/', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data'], name='app_evento_data_411be7_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['responsavel'], name='app_evento_respons_b3e089_idx'),
        ),
    ]
