# Generated by Django 5.2.7 on 2026-03-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_add_ordem_servico_lubrificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutentor',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica se o manutentor faz parte da equipe', verbose_name='Ativo'),
        ),
    ]
