# Generated by Django 5.2.7 on 2026-03-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_add_ativo_to_manutentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutentor',
            name='horas_semanais',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade de horas trabalhadas por semana', max_digits=5, null=True, verbose_name='Horas Semanais'),
        ),
    ]
