# Generated by Django 6.0 on 2026-03-22 02:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_add_horas_semanais_to_manutentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosMaoDeObra',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('tempo_padrao_inspecao_preventiva_horas', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Usado no cálculo do Plano Preventiva quando o roteiro não informa tempo (ex.: 0,50 = 30 min).', max_digits=8, verbose_name='Tempo padrão — Ordens de Inspeção Preventiva (horas)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Parâmetros de Mão de Obra',
                'verbose_name_plural': 'Parâmetros de Mão de Obra',
            },
        ),
    ]
