# Generated by Django 5.2.7 on 2026-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_parametros_mao_de_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparadamaquina',
            name='dias_produtivos',
            field=models.JSONField(blank=True, default=list, verbose_name='Dias produtivos'),
        ),
    ]
