# Generated by Django 5.2.7 on 2026-04-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_config_parada_dias_produtivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoReuniaoPCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título do assunto')),
                ('duracao_minutos', models.PositiveIntegerField(default=15, verbose_name='Duração (minutos)')),
                ('permite_upload', models.BooleanField(default=False, help_text='Se marcado, a reunião pode receber arquivo neste assunto.', verbose_name='Permite upload de arquivo')),
                ('data_reuniao', models.DateField(verbose_name='Data da reunião')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem na pauta')),
            ],
            options={
                'verbose_name': 'Assunto Reunião PCM',
                'verbose_name_plural': 'Assuntos Reunião PCM',
                'ordering': ['data_reuniao', 'ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='assuntoreuniaopcm',
            index=models.Index(fields=['data_reuniao'], name='app_assunto_data_re_2d40f3_idx'),
        ),
    ]
