# Generated by Django 5.2.7 on 2026-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_assunto_reuniao_pcm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuntoreuniaopcm',
            name='permite_upload',
        ),
        migrations.AddField(
            model_name='assuntoreuniaopcm',
            name='arquivo',
            field=models.FileField(
                blank=True,
                help_text='Arquivo opcional vinculado a este assunto (apresentação, planilha, etc.).',
                null=True,
                upload_to='reuniao_pcm/assuntos/',
                verbose_name='Arquivo anexo',
            ),
        ),
    ]
