# Generated by Django 5.2.7 on 2026-04-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_origemimpactoorcamento_and_percentual_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiropreventiva',
            name='dt_entrada',
            field=models.CharField(
                blank=True,
                help_text='Próxima data da ação (import CSV DT_ENTRADA); usada no calendário da máquina com período do PlanoPreventiva',
                max_length=50,
                null=True,
                verbose_name='Data Entrada',
            ),
        ),
    ]
