# Generated by Django 5.2.7 on 2026-05-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_roteiropreventiva_dt_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAurora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aurora', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código Aurora')),
                ('descricao_aurora', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Aurora')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Unitário')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Excluir da lista sem apagar o registro', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Item Aurora',
                'verbose_name_plural': 'Itens Aurora',
                'ordering': ['codigo_aurora'],
            },
        ),
        migrations.AddIndex(
            model_name='itemaurora',
            index=models.Index(fields=['ativo'], name='app_itemaur_ativo_6c8ee5_idx'),
        ),
    ]
