# Generated by Django 5.2.7 on 2026-05-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_item_aurora'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configlinhaproducaocentroatividade',
            new_name='app_configl_descr_l_b3312e_idx',
            old_name='app_configl_descr_l_idx',
        ),
        migrations.RenameIndex(
            model_name='origemimpactoorcamento',
            new_name='app_origemi_tipo_or_938503_idx',
            old_name='app_origemi_tipo_or_b24f79_idx',
        ),
        migrations.RenameIndex(
            model_name='origemimpactoorcamento',
            new_name='app_origemi_setor_p_d1d858_idx',
            old_name='app_origemi_setor_p_3364ef_idx',
        ),
        migrations.RenameIndex(
            model_name='paradamaquinaos',
            new_name='app_paradam_os_nume_0282d8_idx',
            old_name='app_paradam_os_nume_idx',
        ),
        migrations.RenameIndex(
            model_name='percentualimpactosetor',
            new_name='app_percent_origem__d74222_idx',
            old_name='app_percent_origem__38c9b1_idx',
        ),
        migrations.RenameIndex(
            model_name='percentualimpactosetor',
            new_name='app_percent_ativo_a3ad99_idx',
            old_name='app_percent_ativo_4afab3_idx',
        ),
        migrations.AddField(
            model_name='centroatividade',
            name='imagem',
            field=models.CharField(blank=True, help_text='Caminho da imagem (relativo a static/)', max_length=500, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='manutentor',
            name='local_trab',
            field=models.CharField(choices=[('Industria', 'Industria'), ('Frigorífico', 'Frigorífico'), ('Civil', 'Civil'), ('Externa', 'Externa'), ('Indefinido', 'Indefinido'), ('ETE/ETA', 'ETE/ETA'), ('Utilidades', 'Utilidades'), ('Melhoria', 'Melhoria'), ('Ferramentaria', 'Ferramentaria'), ('Tornearia', 'Tornearia'), ('Lubrificação', 'Lubrificação'), ('Automação', 'Automação'), ('Manutenção', 'Manutenção')], max_length=40, verbose_name='Local de Trabalho'),
        ),
    ]
