# Generated by Django 5.2.7 on 2026-05-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_rename_app_configl_descr_l_idx_app_configl_descr_l_b3312e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemaurora',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemaurora',
            name='codigo_aurora',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Código Aurora'),
        ),
    ]
