# Generated by Django 5.2.7 on 2026-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_item_aurora_codigo_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueAlmoxarifado',
            fields=[
                ('codigo_unidade', models.IntegerField(blank=True, null=True, verbose_name='Código Unidade')),
                ('nome_unidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Unidade')),
                ('codigo_deposito', models.IntegerField(blank=True, null=True, verbose_name='Código Depósito')),
                ('descricao_deposito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Depósito')),
                ('codigo_local', models.IntegerField(blank=True, null=True, verbose_name='Código Local')),
                ('descricao_local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Local')),
                ('estante', models.IntegerField(blank=True, null=True, verbose_name='Estante')),
                ('prateleira', models.IntegerField(blank=True, null=True, verbose_name='Prateleira')),
                ('coluna', models.IntegerField(blank=True, null=True, verbose_name='Coluna')),
                ('sequencia', models.IntegerField(blank=True, null=True, verbose_name='Sequência')),
                ('codigo_destino_uso', models.IntegerField(blank=True, null=True, verbose_name='Código Destino Uso')),
                ('descricao_destino_uso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Destino Uso')),
                ('codigo_item', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Código Item')),
                ('descricao_item', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição Item')),
                ('codigo_grupo_estoque', models.IntegerField(blank=True, null=True, verbose_name='Código Grupo Estoque')),
                ('descricao_grupo_estoque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Grupo Estoque')),
                ('codigo_subgrupo_estoque', models.IntegerField(blank=True, null=True, verbose_name='Código Subgrupo Estoque')),
                ('descricao_subgrupo_estoque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Subgrupo Estoque')),
                ('unidade_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade Medida')),
                ('data_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Data Última Compra')),
                ('codigo_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Lote')),
                ('legenda_lote', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda Lote')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor')),
                ('situacao_pilha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação Pilha')),
                ('data_criacao_registro', models.DateTimeField(blank=True, null=True, verbose_name='Data Criação (ERP)')),
                ('marca_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca Referência')),
                ('controla_estoque_minimo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Controla Estoque Mínimo')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Fechamento')),
                ('data_geracao', models.DateTimeField(blank=True, null=True, verbose_name='Data Geração')),
                ('classificacao_tempo_sem_consumo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classificação Tempo Sem Consumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Estoque Almoxarifado',
                'verbose_name_plural': 'Estoques Almoxarifado',
                'ordering': ['codigo_item'],
            },
        ),
    ]
