# Generated by Django 5.2.7 on 2026-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_estoque_almoxarifado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaurora',
            name='status_item',
            field=models.CharField(blank=True, db_index=True, help_text='Situação do item no catálogo (ex.: ativo, obsoleto, bloqueado — texto livre ou código interno)', max_length=120, null=True, verbose_name='Status do Item'),
        ),
    ]
