# Generated by Django 5.2.7 on 2026-05-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_item_aurora_status_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(db_index=True, max_length=255, verbose_name='Fabricante')),
                ('codigo_item', models.CharField(db_index=True, max_length=120, verbose_name='Código do item')),
                ('posicao_no_manual', models.CharField(blank=True, help_text='Ex.: página, figura ou seção do manual do fabricante', max_length=255, null=True, verbose_name='Posição no manual')),
                ('descricao_fabricante', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição do fabricante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Peça Fornecedor',
                'verbose_name_plural': 'Peças Fornecedor',
                'ordering': ['fabricante', 'codigo_item'],
                'indexes': [models.Index(fields=['fabricante', 'codigo_item'], name='app_pecafor_fabrica_292f9e_idx')],
            },
        ),
    ]
