# Generated by Django 5.2.7 on 2026-05-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_peca_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fabricante', models.CharField(db_index=True, help_text='Código como aparece no manual da máquina (geralmente igual ao código em Peça Fornecedor)', max_length=120, verbose_name='Código do fabricante')),
                ('parte_maquina', models.CharField(blank=True, help_text='Denominação ou posição da peça no manual da máquina', max_length=500, null=True, verbose_name='Parte da máquina')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_maquina_manual', to='app.maquina', to_field='cd_maquina', verbose_name='Máquina')),
                ('peca_fornecedor', models.ForeignKey(help_text='Registro em Peça Fornecedor (fabricante e código do item)', on_delete=django.db.models.deletion.PROTECT, related_name='pecas_maquina', to='app.pecafornecedor', verbose_name='Peça fornecedor')),
            ],
            options={
                'verbose_name': 'Peça da Máquina (manual)',
                'verbose_name_plural': 'Peças da Máquina (manual)',
                'ordering': ['maquina__cd_maquina', 'codigo_fabricante'],
                'indexes': [models.Index(fields=['maquina', 'peca_fornecedor'], name='app_pecamaq_maquina_e4cf80_idx')],
            },
        ),
    ]
