# Generated by Django 5.2.7 on 2026-05-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_peca_maquina_manual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PecaMaquina',
            new_name='PecaMaquinaCitadoManual',
        ),
        migrations.AlterModelOptions(
            name='pecamaquinacitadomanual',
            options={'ordering': ['maquina__cd_maquina', 'codigo_fabricante'], 'verbose_name': 'Peça da máquina citada no manual', 'verbose_name_plural': 'Peças da máquina citadas no manual'},
        ),
        migrations.RenameIndex(
            model_name='pecamaquinacitadomanual',
            new_name='app_pecamaq_maquina_5a4507_idx',
            old_name='app_pecamaq_maquina_e4cf80_idx',
        ),
    ]
