# Generated by Django 5.2.7 on 2026-05-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_rename_peca_maquina_citado_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecamaquinacitadomanual',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade indicada na lista de peças (ex.: coluna QTDE no manual)', max_digits=15, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pecamaquinacitadomanual',
            name='peca_fornecedor',
            field=models.ForeignKey(help_text='Nome ou Descrição em Peça Fornecedor (fabricante e código do item)', on_delete=django.db.models.deletion.PROTECT, related_name='pecas_maquina', to='app.pecafornecedor', verbose_name='Peça fornecedor'),
        ),
    ]
