# Generated by Django 5.2.7 on 2026-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_pecamaquinacitadomanual_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecamaquinacitadomanual',
            name='fabricante',
            field=models.CharField(blank=True, db_index=True, help_text='Fabricante conforme a lista/manual (cópia desnormalizada; pode coincidir com Peça Fornecedor)', max_length=255, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='pecamaquinacitadomanual',
            name='posicao_no_manual',
            field=models.CharField(blank=True, help_text='Posição no manual da peça neste contexto de máquina (ex.: coluna «Posição (manual)» na lista)', max_length=255, null=True, verbose_name='Posição no manual'),
        ),
    ]
