# Generated by Django 5.2.7 on 2026-05-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_pecamanualcatalogo_and_pmcm_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pecamaquinacitadomanual',
            options={'ordering': ['maquina__cd_maquina', 'peca_catalogo__codigo_fabricante'], 'verbose_name': 'Peça da máquina citada no manual', 'verbose_name_plural': 'Peças da máquina citadas no manual'},
        ),
        migrations.RenameIndex(
            model_name='pecamaquinacitadomanual',
            new_name='app_pecamaq_maquina_022ccd_idx',
            old_name='app_pmcm_maquina_cat_idx',
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='classificacao_inclusao_almox',
            field=models.CharField(blank=True, help_text='Coluna «Classificação de inclusão no almox.» (R) na LISTA COMPLETA.', max_length=500, null=True, verbose_name='Classificação inclusão almox.'),
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='estoque_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coluna «Estoque máximo» (K) na LISTA COMPLETA.', max_digits=15, null=True, verbose_name='Estoque máximo'),
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='estoque_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coluna «Estoque mínimo» (J) na LISTA COMPLETA.', max_digits=15, null=True, verbose_name='Estoque mínimo'),
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='observacao',
            field=models.TextField(blank=True, help_text='Coluna «Observação» (T) na LISTA COMPLETA.', null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='troca_conforme',
            field=models.TextField(blank=True, help_text='Coluna «Troca conforme» (Q) na LISTA COMPLETA.', null=True, verbose_name='Troca conforme'),
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='valor_estoque_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coluna «Valor est. máximo» (M) na LISTA COMPLETA.', max_digits=15, null=True, verbose_name='Valor est. máximo'),
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='valor_estoque_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coluna «Valor est. mínimo» (L) na LISTA COMPLETA.', max_digits=15, null=True, verbose_name='Valor est. mínimo'),
        ),
        migrations.AddField(
            model_name='itemaurora',
            name='vida_util_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coluna «Vida útil (horas)» (O) na LISTA COMPLETA.', max_digits=12, null=True, verbose_name='Vida útil (horas)'),
        ),
        migrations.AlterField(
            model_name='itemaurora',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coluna «Valor unitário» (I) na LISTA COMPLETA.', max_digits=15, null=True, verbose_name='Valor Unitário'),
        ),
    ]
