# Generated by Django 5.2.7 on 2026-05-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_itemaurora_lista_completa_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecamanualcatalogo',
            name='item_aurora',
            field=models.ForeignKey(blank=True, help_text='Referência ao código interno Aurora na mesma linha da LISTA COMPLETA (col. G); associa fabricante + cód. fabricante ao item único usado pela empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_catalogo_manual', to='app.itemaurora', verbose_name='Item Aurora (código interno)'),
        ),
    ]
