# Generated by Django 5.2.7 on 2026-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_peca_manual_catalogo_item_aurora_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlercenf',
            name='torno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Torno?'),
        ),
    ]
