# Generated by Django 5.2.7 on 2026-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_assuntoreuniaopcmarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='status_manual',
            field=models.BooleanField(db_index=True, default=True, help_text='Define se este registro deve ser considerado nos cálculos do sistema.', verbose_name='Considerar nos cálculos'),
        ),
    ]
