# Generated by Django 5.2.7 on 2026-05-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_remove_controlercenf_torno_notafiscal_status_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutentor',
            name='local_trab',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Texto livre (ex.: coluna LOCAL na importação HR).',
                max_length=255,
                verbose_name='Local de Trabalho',
            ),
        ),
    ]
