# Generated by Django 5.2.7 on 2026-05-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_manutentor_local_trab_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutentor',
            name='setor_trabalho',
            field=models.CharField(
                choices=[
                    ('Industria', 'Industria'),
                    ('Frigorífico', 'Frigorífico'),
                    ('Civil', 'Civil'),
                    ('Externa', 'Externa'),
                    ('Indefinido', 'Indefinido'),
                    ('ETE/ETA', 'ETE/ETA'),
                    ('Utilidades', 'Utilidades'),
                    ('Melhoria', 'Melhoria'),
                    ('Ferramentaria', 'Ferramentaria'),
                    ('Tornearia', 'Tornearia'),
                    ('Lubrificação', 'Lubrificação'),
                    ('Automação', 'Automação'),
                    ('Manutenção', 'Manutenção'),
                ],
                default='Indefinido',
                max_length=50,
                verbose_name='Setor de Trabalho',
            ),
        ),
    ]
